name: auto deploy

on:
  pull_request:
    branches:
      - test
#    types:
#      - closed

jobs:
  push_to_registry:
    name: PUSH to NCP
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Login to NCP
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.NCP_REGISTRY }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/dockerfile
          push: true
          tags: ${{ secrets.NCP_REGISTRY }}/nest:latest
          cache-from: type=registry,ref=${{ secrets.NCP_REGISTRY }}/nest:latest
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}