name: CI

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd backend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test